name: "Macaron Security Analysis"
description: "Run Macaron to analyze supply chain security"
author: "Oracle - github.com/oracle/macaron"

inputs:
  policy_name:
    description: "Using pre-define policies"
  policy_file:
    description: "Path to custom policy_file"
  deps_depth:
    description: "Depth for dependency analysis"
  output_dir:
    description: "Directory to store analysis reports"
    default: "output"

outputs:
  status:
    description: "Pass/Fail status of the analysis"
    value: ${{ steps.run-macaron-policy-verification.outputs.status }}
  report:
    description: "Path to the Macaron analysis report"
    value: ${{ steps.run-macaron-analysis.outputs.report }}
  vsa:
    description: "Verification Summary Attestation"
    value: ${{ steps.run-macaron-policy-verification.outputs.vsa }}

runs:
  using: "composite"
  steps:
    - name: Cache Macaron setup
      id: cache-macaron
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/macaron
        key: macaron-setup-0.16.0

    - name: Setup Macaron
      if: steps.cache-macaron.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ runner.temp }}/macaron
        curl -o ${{ runner.temp }}/macaron/run_macaron.sh https://raw.githubusercontent.com/oracle/macaron/release/scripts/release_scripts/run_macaron.sh
        chmod +x ${{ runner.temp }}/macaron/run_macaron.sh
      shell: bash

    - name: Run Macaron Analysis
      id: run-macaron-analysis
      run: |
        CMD="${{ runner.temp }}/macaron/run_macaron.sh --output-dir ${{ inputs.output_dir }} -lr . analyze -rp ."

        if [ -n "${{ inputs.deps_depth }}" ]; then
          CMD="$CMD --deps-depth ${{ inputs.deps_depth }}"
        fi

        eval "$CMD"

        if [ $? -eq 0 ]; then
          echo "report=report_path" >> $GITHUB_OUTPUT
        else
          echo "Macaron analysis failed."
          exit 1
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run Macaron Policy Verification
      id: run-macaron-policy-verification
      if: ${{ inputs.policy_file }} || ${{ inputs.policy_name }}
      run: |
        if [[ -n "${{ inputs.policy_file }}" && -n "${{ inputs.policy_name }}" ]]; then
          echo "::error::Only one of 'policy_file' or 'policy_name' can be specified, but both were defined."
          exit 1
        fi

        CMD="${{ runner.temp }}/macaron/run_macaron.sh verify-policy --database ${{ inputs.output_dir }}/macaron.db"

        if [ -n "${{ inputs.policy_file }}" ]; then
          CMD="$CMD --file ${{ inputs.policy_file }}"
        fi

        eval "$CMD"

        if [ $? -eq 0 ]; then
          echo "status=pass" >> $GITHUB_OUTPUT
          echo "vsa=vsa_path" >> $GITHUB_OUTPUT
        else
          echo "status=fail" >> "$GITHUB_OUTPUT"
          exit 1
        fi
      shell: bash
