#include "prelude.dl"

Policy("has-verified-provenance-urllib3", component_id, "Require a verified provenance file for urllib3.") :-
    check_passed(component_id, "mcn_provenance_derived_repo_1"),
    check_passed(component_id, "mcn_provenance_derived_commit_1"),
    check_passed(component_id, "mcn_provenance_verified_1").

apply_policy_to("has-verified-provenance-urllib3", component_id) :-
    is_component(component_id, purl),
    match("pkg:pypi/urllib3@.*", purl).
